<HTML>
<HEAD>
<TITLE>catch/3</TITLE>
</HEAD><BODY>
<A NAME="aa1f4e94"></A><B>catch/3
<P></P>
<A NAME="4226cb14"></A><A NAME="23c049d2"></A><A NAME="422801d5"></A></B>catch/3 –  execute a goal, specifying an exception handler
<P></P>
<A NAME="23c049d3"></A><A NAME="4405ea10"></A>throw/1 –  give control to exception handler
<P></P>
<A NAME="23c049d4"></A><B>FORMS
<P></P>
<A NAME="23c049d5"></A></B>catch(Goal,Pattern,ExceptionGoal) 
<P></P>
<A NAME="23c049d6"></A>throw(Reason) 
<P></P>
<A NAME="23c049d7"></A><B>DESCRIPTION  
<P></P>
<A NAME="23c049d8"></A></B>catch/3 provides a facility for catching errors or exceptions and handling them
gracefully.  Execution of catch/3 will cause the goal Goal to be executed.  If no errors or throws occur during
the execution of Goal, then catch/3 behaves just as if call/1 were called with Goal.  Goal may succeed thus giving control to portions of the program outside the scope
of the catch.  Failures in these portions of the program may cause reexecution
(via backtracking) of goals in the scope of the catch of which Goal is the ancestor.
<P></P>
<A NAME="23c04a04"></A>If a goal of the form throw(Reason) is encountered during the execution of Goal or in any subsequent reexecution of Goal, then the goal ExceptionGoal of the catch with the innermost scope capable of unifying Reason and Pattern together will be executed with this unification intact.  Once started, the
execution of the goal ExceptionGoal behaves just like the execution of any other goal. The goal ExceptionGoal is outside of the scope of the catch which initiated the execution of ExceptionGoal so any throws encountered during the execution of ExceptionGoal will be handled by catches which are ancestors of the catch which initiated
the execution of ExceptionGoal.  This means that a handler may catch some fairly general pattern, deal with
some aspects for which it is prepared for, but throw back to some earlier
handler for those aspects for which it is not.
<P></P>
<A NAME="23c049fb"></A>Many of the builtins will cause an error if the types of the arguments to the
builtin are wrong.  There are other reasons for errors such as exhausting a
certain resource.  Whatever the cause, an error occurring during the execution of
a goal causes throw/1 to be executed.  The effect is as if the goal which caused the error where
replaced by a goal throw(error(ErrorTerm, ErrorInfo)) where ErrorTerm and ErrorInfo supply information about the error.  ErrorTerm is mandated by ISO Prolog Standard.  ErrorInfo is an implementation defined (and therefore specific) term which may or may
not provide additional information about the error.
<P></P>
<A NAME="23c049fc"></A>The ISO Prolog Standard specifies that ErrorTerm be one of the following forms:
<P></P>
<A NAME="23c049fd"></A>instantiation_error – An argument or one of its components is a variable. 
<P></P>
<A NAME="23c049fe"></A>type_error(ValidType,Culprit) – An argument or one of its components is of the incorrect type.  ValidType may be any one of the following atoms: atom, body, callable, character,
compound, constant, integer, list, number, variable.  Culprit is the argument or component which was of the incorrect type.
<P></P>
<A NAME="23c049ff"></A>domain_error(ValidDomain,Culprit – The base type of an argument is correct, but the value is outside the
domain for which the predicate is defined.  The ISO Prolog Standard states that ValidDomain may be any one of the following atoms: character_code_list, character_list, close_option, flag_value, io_mode, not_less_than_zero, operator_priority, operator_specifier, prolog_flag, read_option, source_sink, stream_or_alias, stream_option, stream_position, write_option.  ALS Prolog allows ValidDomain to take on these additional values: depth_computation, line_length, positive_integer. Culprit is the argument which caused the error.
<P></P>
<A NAME="23c04a00"></A>existence_error(ObjectType,Culprit) – An operation is attempted on a certain type of object specified by ObjectType does not exist. Culprit is the nonexistent object on which the operation was attempted. ObjectType may take on the following values: operator, past_end_of_stream, procedure, static_procedure, source_sink, stream.
<P></P>
<A NAME="23c04a01"></A>permission_error(Operation,ObjectType,Culprit) – Operation is an operation not permitted on object type ObjectType.  Culprit is the object on which the error occurred.  ObjectType is an atom taking on values as described above.  Operation may be one of the following atoms:  access_clause, create, input, modify, open, output, reposition.
<P></P>
<A NAME="23c04a02"></A>representation_error(Flag) – The implementation defined limit indicated by Flag has been breached.  Flag may be one of the following atoms:  character, character_code, exceeded_max_arity, flag.
<P></P>
<A NAME="23c04a03"></A>calculation_error(CalcFlag) – An arithmetic operation result in an exceptional value as indicated by the
atom CalcFlag.  CalcFlag may take on the following values: overflow, underflow, zero_divide, undefined.
<P></P>
<A NAME="23c04a2f"></A>resource_error(Resource) – There are insufficient resources to complete execution.  The type of
resource exhausted is indicated by the implementation defined term Resource.
<P></P>
<A NAME="23c04a26"></A>syntax_error – A sequence of characters being read by read_term/4 can not be parsed with the current operator definitions.  The reason for the
syntax error (in ALS Prolog) is given in the implementation defined ErrorInfo (see below).
<P></P>
<A NAME="23c04a27"></A>system_error – Other sorts of errors.  These will commonly be operating system related
errors such as being unable to complete a write operation due to the disk being
full.  Additional details about this type of error might be found in the
implementation defined term ErrorInfo.
<P></P>
<A NAME="23c04a28"></A>In ALS Prolog, ErrorInfo is a list providing additional information where the ISO Prolog Standard
mandated term ErrorTerm falls short.  The terms which may be on this list take the following forms:
<P></P>
<A NAME="23c04a29"></A>M:G – The predicate in which the error occurred was in module M on goal G.  Due to the compiled nature of ALS Prolog, it is not always possible to
obtain all of the arguments to the goal G. Those which could not be obtained are indicated as such by the atom '?'.  For this reason, the form M:G should be used for informational purposes only.
<P></P>
<A NAME="23c04a2a"></A>errno(ErrNo) – This form is used to further elaborate on the reason that a system_error occurred.  The errno/1 form indicates that a system call failed.  The value of ErrNo is an integer which indicates the nature of the system error.  The values
that ErrNo take on may vary from system to system.  ALS is looking at a symbolic
way of providing this information.
<P></P>
<A NAME="23c04a2b"></A>syntax(Context,ErrorMessage,LineNumber,Stream) – This form is used to provide additional information about system errors. Context is an atom providing some information about the context in which the error
occurred.  ErrorMessage is an atom providing the text of the message for the error.  LineNumber is the number of the line near which the syntax error occurred.  Stream is the stream which was being read when the syntax error occurred.
<P></P>
<A NAME="23c04a2c"></A><B>EXAMPLES  
<P></P>
<A NAME="23c04a2d"></A></B>Attempt to open a non-existent file.
<P></P>
<A NAME="23c04a2e"></A>?- open(wombat,read,S).
<P></P>
<A NAME="23c04a5a"></A>
<P></P>
<A NAME="23c04a51"></A>Error: The open operation is not permitted on the source_sink object `wombat'.
<P></P>
<A NAME="23c04a52"></A>- Goal:          sio:open(wombat,read,_A,?)
<P></P>
<A NAME="23c04a53"></A>- Throw pattern: error(permission_error(open,source_sink,wombat),
<P></P>
 <A NAME="23c04a54"></A>                     [sio:open(wombat,read,_A,?)])
<P></P>
<A NAME="23c04a55"></A>
<P></P>
<A NAME="23c04a56"></A>Define open_for_read/2 which detects permission errors and prints a message.
<P></P>
<A NAME="23c04a57"></A>
<P></P>
<A NAME="23c04a58"></A>?- consult(user).
<P></P>
<A NAME="23c04a59"></A>Consulting user ...
<P></P>
<A NAME="23c04a85"></A>open_for_read(File, Stream) :-
<P></P>
<A NAME="23c04a7c"></A>        catch( open(File, read, Stream),
<P></P>
<A NAME="23c04a7d"></A>               error(permission_error(open, source_sink, File),_),
<P></P>
<A NAME="23c04a7e"></A>               printf(user_output,&quot;Cannot open %s\n&quot;,[File]) ),
<P></P>
  <A NAME="23c04a7f"></A>    !.
<P></P>
<A NAME="23c04a80"></A>user consulted
<P></P>
<A NAME="23c04a81"></A>
<P></P>
<A NAME="23c04a82"></A>yes.
<P></P>
<A NAME="23c04a83"></A>
<P></P>
<A NAME="23c04a84"></A>Try out open_for_read/2 with a non-existent file.
<P></P>
<A NAME="23c04ab0"></A>
<P></P>
<A NAME="23c04aa7"></A>?- open_for_read(wombat,S).
<P></P>
<A NAME="23c04aa8"></A>Cannot open wombat
<P></P>
<A NAME="23c04aa9"></A>
<P></P>
<A NAME="23c04aaa"></A>S = S
<P></P>
<A NAME="23c04aab"></A>
<P></P>
<A NAME="23c04aac"></A>yes.
<P></P>
<A NAME="23c04aad"></A>
<P></P>
<A NAME="23c04aae"></A>Try out open_for_read/2 with a variable.
<P></P>
<A NAME="23c04aaf"></A>
<P></P>
<A NAME="23c04adb"></A>?- open_for_read(_, S).
<P></P>
<A NAME="23c04ad2"></A>
<P></P>
<A NAME="23c04ad3"></A>Error: Instantiation error.
<P></P>
<A NAME="23c04ad4"></A>- Goal:          sio:open(_A,read,_B,[type(text)])
<P></P>
<A NAME="23c04ad5"></A>- Throw pattern: error(instantiation_error,
<P></P>
<A NAME="23c04ad6"></A>                     [sio:open(_A,read,_B,*)])
<P></P>
<A NAME="23c04ad7"></A>Define a procedure integer_list/2 to illustrate a use of throw/1. Note that il/2 builds the list and throws the result back at the appropriate time.
<P></P>
<A NAME="23c04ad8"></A>?- reconsult(user).
<P></P>
<A NAME="23c04ad9"></A>Reconsulting user ...
<P></P>
<A NAME="23c04ada"></A>integer_list(N, List) :-
<P></P>
  <A NAME="23c0523f"></A>catch( il(N,[]), int_list(List), true),
<P></P>
  <A NAME="23c05236"></A>!.
<P></P>
<A NAME="23c05237"></A>
<P></P>
<A NAME="23c05238"></A>il(0,L) :- throw(int_list(L)).
<P></P>
<A NAME="23c05239"></A>il(N,L) :- NN is N-1, il(NN, [N | L]).
<P></P>
<A NAME="23c0523a"></A>user reconsulted
<P></P>
<A NAME="23c0523b"></A>
<P></P>
<A NAME="23c0523c"></A>yes.
<P></P>
<A NAME="23c0523d"></A>?- integer_list(8,L).
<P></P>
<A NAME="23c0523e"></A>
<P></P>
<A NAME="23c050bc"></A>L = [1,2,3,4,5,6,7,8]
<P></P>
<A NAME="23c050b3"></A>
<P></P>
<A NAME="23c050b4"></A>yes.
<P></P>
<A NAME="23c050b5"></A><B>ERRORS
<P></P>
<A NAME="23c050b6"></A></B>Goal is a variable
<P></P>
<A NAME="23c050b7"></A>----&gt;  instantiation_error.
<P></P>
<A NAME="23c050b8"></A>Goal is not a callable term
<P></P>
<A NAME="23c050b9"></A>----&gt;  type_error(callable,Goal).  [not yet implemented]
<P></P>
<A NAME="23c050ba"></A>Reason does not unify with Pattern in any call of catch/3
<P></P>
<A NAME="23c050bb"></A>----&gt;  system_error.    [not yet implemented]
<P></P>
<A NAME="23c050e7"></A><B>NOTES  
<P></P>
<A NAME="23c050de"></A></B>In the present implementation of ALS Prolog, catch/3 leaves a choice point which is used to restore the scope of the catch when backtracked into.  This choice point remains around even for determinate
goals which are called from catch.  Thus when catch succeeds, you should assume that a choice point has been created.  If the
program should be determinate, a cut should be placed immediately after the catch.  It is expected that at some point in the future, this unfortunate aspect of
ALS Prolog will be fixed, thus obviating the need for an explicit cut.
<P></P>
<A NAME="23c050df"></A>If throw/1 is called with Reason instantiated to a pattern which does not match Pattern in any call of catch/3, control will return to the program which started the Prolog environment.
This usually means that Prolog silently exits to an operating system shell.  When
using the development environment, however, the Prolog shell establishes a
handler for catching uncaught throws or errors thus avoiding this unceremonious
exit from the Prolog system.  It is occassionally possible, particularly with
resource errors, to end up in this last chance handler only to have another error
occur in attempting to handle the error.   Since no handler exists to handle
this error, control returns to the operating system often with no indication of
what went wrong.
<P></P>
</BODY>
</HTML>